import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor:'#9448DA',
    },
    backgroundContainer: {
        height: 230,
        width: '100%',
        backgroundColor: '#FFFFFF',
    },
    backgroundImage: {
        height: 230,
        width: '100%',
        resizeMode: 'cover',
    },
    contentContainer:{
        flex: 1,
        backgroundColor: 'white',
        borderTopLeftRadius: 20,
        borderTopRightRadius: 20,
        marginTop: -20,
    },
    headerContainer:{
        width: '100%',
        justifyContent: 'left',
        alignItems: 'left',
        marginTop: 30,
    },
    headerText:{
        fontSize: 24,
        fontWeight: '800',
        marginLeft: 15,
        color: '#9448DA',
    },
    introContainer:{
        width: '100%',
        justifyContent: 'left',
        alignItems: 'left',
        marginTop: 15,
        marginBottom: 20,
    },
    introText:{
        fontSize: 14,
        marginLeft: 15,
        marginRight: 15,
        color: '#777777',
    },
    subTextOneContainer:{
        width: '100%',
        justifyContent: 'center',
        alignItems: 'center',
        marginTop: 5,
    },  
    subTextTwoContainer:{
        width: '70%',
        marginLeft: '15%',
        marginRight: '15%',
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 40,
        // alignContent: 'center',
    }, 
    subTextOne:{
        fontSize: 20,
        fontWeight: '800',
        color: '#5C2D86',
    },
    subTextTwo:{
        fontSize: 18,
        fontWeight: '700',
        color: '#777777',
        textAlign: 'center',
    },
    carouselContainer:{
        // width: '100%',
        // height: 150,
        // justifyContent: 'center',
        // alignItems: 'center',
        marginTop: 15,
        marginBottom: 10,
    },
    sliderContainer:{
        marginTop: 10,
        width: '100%',
        justifyContent: 'center',
        alignItems: 'center',
    },
    scrollViewStyle:{
        width: '100%',
        height: 280,
        marginLeft: 10,
    },
    slide:{
        width: 290,
        height: 280,
        marginLeft: 20,
    },
    imageView:{
        width: "90%",
        height: 180,
        borderRadius: 14,
        overflow: 'hidden',
        // Add shadow
        shadowColor: "#000000",
        backgroundColor: '#fff',
        shadowOffset: {
            width: 0,
            height: 4,
        },
        shadowOpacity: 0.15,
        shadowRadius: 12,
        elevation: 4,
    },
    image:{
        width: "100%",
        height: "100%",
        resizeMode: 'cover',
    },
    textContainer:{
        marginTop: 10,
        width: '76%',
        marginLeft: '7.5%',
        marginRight: '7.5%',
        justifyContent: 'center',
        alignItems: 'center',
    },
    text:{
        textAlign: 'center',
        fontSize: 13,
        color: '#777777',
        fontWeight: 'bold',
    },
    dropdownContainer:{
        width: '100%',
        marginTop: 20,
        marginBottom: 60,
    },
    galleryParentContainer:{
        width: '100%',
        height: 250,
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 40,
        marginTop: 10,
    },
    galleryScrollStyle:{
        width: '100%',
        height: 250,
    },
    galeriContainer:{
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        paddingRight: 10,
        marginLeft: 10,
    },
    galeriItemContainer:{
        width: 280,
        height: 230,
        marginLeft: 20,
        marginRight: 20,
        borderRadius: 14,
        overflow: 'hidden',
        shadowColor: "#000000",
        backgroundColor: '#fff',
        shadowOffset: {
            width: 0,
            height: 4,
        },
        shadowOpacity: 0.15,
        shadowRadius: 12,
        elevation: 4,
    },
    galeriImage:{
        width: "100%",
        height: "100%",
        resizeMode: 'cover',
    },
    buttonContainer:{
        width: '100%',
        justifyContent: 'center',
        alignItems: 'center',
    },
    buttonViewOne:{
        alignItems: "center",
        height: 45,
        width: "80%",
        backgroundColor: "#9448DA",
        justifyContent: "center",
        alignContent: "center",
        alignSelf: "center",
        borderRadius: 10,
        borderWidth: 1,
        borderColor: "#973BD9",
    },
    buttonViewTwo:{
        alignItems: "center",
        marginTop: "8%",
        height: 45,
        width: "80%",
        marginTop: 10,
        justifyContent: "center",
        alignContent: "center",
        alignSelf: "center",
        borderRadius: 10,
        borderWidth: 1,
        borderColor: "#973BD9",
    },
    buttonTextOne:{
        alignItems: "center",
        color: "#FFF",
        textAlign: "center",
        fontSize: 16,
        fontStyle: "normal",
        fontWeight: "700",
    },
    buttonTextTwo:{
        color: "#9448DA",
        fontSize: 16,
        fontStyle: "normal",
        fontWeight: "700",
    },
    ticketContainer:{
        width: '100%',
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 40,
        // backgroundColor: 'yellow',
    },
    ticketImage:{
        width: 280,
        height: 100,
        resizeMode: 'contain',
    },
    bulletContainer:{
        width: '100%',
        marginBottom: 40,
    },
    bulletPointContainer:{
        width: '100%',
        // marginBottom: 10,
        borderColor: '#DDDDDD',
        borderBottomWidth: 1,
    },
    textContainer:{
        width: '85%',
        flexDirection: 'row',
        alignItems: 'center',
        marginLeft: 20,
        marginTop: 5,
        marginBottom: 5,
    },
    bullet:{
        fontSize: 14,
        color: '#777777',
        marginRight: 10,
    },
    bulletPointText:{
        fontSize: 14,
        color: '#777777',
    },
});

export default styles;