import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor:'#9448DA',
    },
    backgroundContainer: {
        height: 230,
        width: '100%',
        backgroundColor: '#FFFFFF',
    },
    backgroundImage: {
        height: 230,
        width: '100%',
        resizeMode: 'cover',
    },
    contentContainer:{
        flex: 1,
        backgroundColor: 'white',
        borderTopLeftRadius: 20,
        borderTopRightRadius: 20,
        marginTop: -20,
    },
    headerContainer:{
        width: '100%',
        justifyContent: 'left',
        alignItems: 'left',
        marginTop: 30,
    },
    headerText:{
        fontSize: 24,
        fontWeight: '800',
        marginLeft: 15,
        color: '#9448DA',
    },
    introContainer:{
        width: '100%',
        justifyContent: 'left',
        alignItems: 'left',
        marginTop: 15,
        marginBottom: 20,
    },
    introText:{
        fontSize: 14,
        marginLeft: 15,
        marginRight: 15,
        color: '#777777',
    },
    subTextOneContainer:{
        width: '100%',
        justifyContent: 'center',
        alignItems: 'center',
        marginTop: 5,
    },  
    subTextTwoContainer:{
        width: '70%',
        marginLeft: '15%',
        marginRight: '15%',
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 40,
        // alignContent: 'center',
    },
    subTextThreeContainer:{
        width: '70%',
        marginLeft: '15%',
        marginRight: '15%',
        justifyContent: 'center',
        alignItems: 'left',
        marginBottom: 40,
        // alignContent: 'center',
    },
    subTextFourContainer: {
        width: '100%',
        flexDirection: 'row',
        justifyContent: 'flex-start',
        alignItems: 'flex-start',
        marginLeft: 15,
        flexShrink: 1,
        flexWrap: 'wrap',
    }, 
    subTextFiveContainer: {
        width: '100%',
        flexDirection: 'row',
        justifyContent: 'flex-start',
        alignItems: 'flex-start',
        marginLeft: 15,
        flexShrink: 1,
        flexWrap: 'wrap',
        marginBottom: 20,
        marginTop: 30,
        zIndex: 0,
    },    
    subTextSixContainer: {
        width: '100%',
        justifyContent: 'center',
        alignItems: 'center',
        marginTop: -190,
      }, 
    subTextOne:{
        fontSize: 20,
        fontWeight: '800',
        color: '#5C2D86',
    },
    subTextTwo:{
        fontSize: 18,
        fontWeight: '700',
        color: '#777777',
        textAlign: 'center',
    },
    subTextThree:{
        fontSize: 18,
        fontWeight: '700',
        color: '#777777',
        textAlign: 'left',
        marginBottom: 10,
        marginTop:10,
        width: '103%',
    },
    dropdownItem: {
        padding: 10,
        borderBottomWidth: 1,
        borderBottomColor: 'rgba(123, 128, 126, 0.18)',
      },
    dropdownContainer: {
        width: '100%',
        marginTop: 20,
        marginBottom: 60,
        marginLeft: 50,
      },
    dropdownItemContainer: {
        backgroundColor: '#F6EEFF',
        borderColor: '#8A4DFE',
        borderWidth: 1,
        paddingVertical: 8,
        paddingHorizontal: 16,
        borderRadius: 8,
        marginBottom: 8,
        width: '90%',
      },
    dropdownPointContainer: {
        flexDirection: 'row',
        alignItems: 'center',
      },
    pointIcon: {
        marginRight: 8,
      },
    dropdownPointText: {
        fontSize: 16,
        color: '#777777',
        flex: 1,
      }, 
    carouselContainer:{
        // width: '100%',
        // height: 150,
        // justifyContent: 'center',
        // alignItems: 'center',
        marginTop: 15,
        marginBottom: 10,
    },
    sliderContainer:{
        marginTop: 10,
        width: '100%',
        justifyContent: 'center',
        alignItems: 'center',
    },
    scrollViewStyle:{
        width: '100%',
        height: 280,
        marginLeft: 10,
    },
    slide:{
        width: 290,
        height: 280,
        marginLeft: 20,
    },
    imageView:{
        width: "90%",
        height: 180,
        borderRadius: 14,
        overflow: 'hidden',
        // Add shadow
        shadowColor: "#000000",
        backgroundColor: '#fff',
        shadowOffset: {
            width: 0,
            height: 4,
        },
        shadowOpacity: 0.15,
        shadowRadius: 12,
        elevation: 4,
    },
    image:{
        width: "100%",
        height: "100%",
        resizeMode: 'cover',
    },
    // subsidiImageContainer: {
    //     position: 'absolute',
    //     top: 800, // Adjust this value based on your layout
    //     left: 0,
    //     right: 0,
    //     bottom: 0,
    //     justifyContent: 'center',
    //     alignItems: 'center',
    //   },
    subsidiMamoImage: {
        aspectRatio: 600 / 1500,
        resizeMode: 'contain',
        marginTop: -250,
    },
    subfertilitiImage: {
        aspectRatio: 600 / 1500,
        resizeMode: 'contain',
        marginTop: -150,
    },
    KaunselingImageContainer: {
        alignItems: 'center',
        justifyContent: 'center',
        textAlign: 'center', // Add this line
        marginTop: 30,
        marginBottom: 20,
    },
    KaunselingImageStyle: {
        ...Platform.select({
            ios: {
                // iOS styles
                marginLeft: '6%',
                resizeMode: 'contain',
                borderRadius: 5,
            },
            android: {
                // Android styles
                marginLeft: '1%',
                resizeMode: 'contain',
                borderRadius: 5,
            },
        }),
    },
    carouselTextContainer:{
        marginTop: 10,
        width: '76%',
        marginLeft: '7.5%',
        marginRight: '7.5%',
        justifyContent: 'center',
        alignItems: 'center',
    },
    text:{
        textAlign: 'center',
        fontSize: 13,
        color: '#777777',
        fontWeight: 'bold',
    },
    dropdownContainer:{
        width: '100%',
        marginTop: 20,
        marginBottom: 60,
    },
    galleryParentContainer:{
        width: '100%',
        height: 250,
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 40,
        marginTop: 10,
    },
    galleryScrollStyle:{
        width: '100%',
        height: 250,
    },
    HPVScrollStyle:{
        // width: '100%',
        height: 250,
    },
    galeriContainer:{
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        paddingRight: 10,
        marginLeft: 10,
    },
    galeriItemContainer:{
        width: 280,
        height: 230,
        marginLeft: 20,
        marginRight: 20,
        borderRadius: 14,
        overflow: 'hidden',
        shadowColor: "#000000",
        backgroundColor: '#fff',
        shadowOffset: {
            width: 0,
            height: 4,
        },
        shadowOpacity: 0.15,
        shadowRadius: 12,
        elevation: 4,
    },
    galeriImage:{
        width: "100%",
        height: "100%",
        resizeMode: 'cover',
    },
    buttonContainer:{
        width: '100%',
        justifyContent: 'center',
        alignItems: 'center',
    },
    subsidiButtonContainer:{
        width: '100%',
        justifyContent: 'center',
        alignItems: 'center',
        marginTop: 30,
    },
    buttonViewOne:{
        alignItems: "center",
        height: 45,
        width: "80%",
        backgroundColor: "#9448DA",
        justifyContent: "center",
        alignContent: "center",
        alignSelf: "center",
        borderRadius: 10,
        borderWidth: 1,
        borderColor: "#973BD9",
    },
    buttonViewTwo:{
        alignItems: "center",
        marginTop: "8%",
        height: 45,
        width: "80%",
        marginTop: 10,
        justifyContent: "center",
        alignContent: "center",
        alignSelf: "center",
        borderRadius: 10,
        borderWidth: 1,
        borderColor: "#973BD9",
    },
    buttonTextOne:{
        alignItems: "center",
        color: "#FFF",
        textAlign: "center",
        fontSize: 16,
        fontStyle: "normal",
        fontWeight: "700",
    },
    buttonTextTwo:{
        color: "#9448DA",
        fontSize: 16,
        fontStyle: "normal",
        fontWeight: "700",
    },
    ticketContainer:{
        width: '100%',
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 40,
        // backgroundColor: 'yellow',
    },
    ticketImage:{
        width: 280,
        height: 100,
        resizeMode: 'contain',
    },
    bulletContainer:{
        width: '100%',
        marginBottom: 40,
        marginTop: 10,
    },
    bulletPointContainer:{
        width: '100%',
        borderColor: '#DDDDDD',
        borderTopWidth: 1,
        paddingVertical: 5,
    },
    subBulletContainer: {
        flexDirection: 'row',
        alignItems: 'flex-start', // Adjust this according to your needs
        marginBottom: 5, // Adjust the space between sub-bullets
      },
    subBullet: {
        fontSize: 14,
        color: '#000',
        marginRight: 5, // Adjust the space between the sub-bullet and the text
      },          
    lastBulletPointContainer: {
        borderBottomWidth: 1,
        borderColor: '#DDDDDD',
        paddingBottom: 10, // Adjust as needed
      },
    textContainer:{
        width: '85%',
        flexDirection: 'row',
        marginLeft: 20,
        marginTop: 5,
        marginBottom: 5,
    },
    bullet:{
        fontSize: 14,
        color: '#777777',
        marginRight: 10,
    },
    bulletPointText:{
        fontSize: 14,
        color: '#777777',
    },
    popupContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'rgba(0,0,0,0.5)',
    },
    popupContent: {
        marginTop: 50,
        width: '100%',
    },
    whiteBox: {
        backgroundColor: '#FFF',
        padding: 20,
        borderRadius: 10,
        width: '90%',
        zIndex: 2,
        // height: '50%',
        alignItems: 'center',
    },
    closeButton: {
        position: 'absolute',
        top: 15,
        right: '50%',
        zIndex: 3,
        transform: [{ translateX: -10 }], 
    },
    closeButtonImage: {
        width: 20, 
        height: 20, 
    },
});

export default styles;